### ISSUE TITLE
peripheral(_:didUpdateValueFor:error:)

### ISSUE THREAD

**Issue by theedov** [StarryInternet/CombineCoreBluetooth#13]
Hi @klundberg ,
Does this library implement [peripheral(_:didUpdateValueFor:error:)](https://developer.apple.com/documentation/corebluetooth/cbperipheraldelegate/1518708-peripheral)? Somehow I can't find it and subscribing to `peripheral.setNotifyValue(true, for: characteristic)`(https://developer.apple.com/documentation/corebluetooth/cbperipheral/1518949-setnotifyvalue) only publishes value once...

// OK, I found the implementation. Weird, when I use plain CoreBluetooth it works as expected and I get values from the device until stopped, but here I only get value once.

// Ahh, `peripheral.listenForUpdates(on: characteristic)` helped.

**Comment by klundberg** [comment]
Yep, setNotifyValue here just responds if the act of setting succeeded, that function you found should do the trick for listening for changes. If the api choices here are confusing though, I'm open to ideas for changing it!

I may move the code out of `Convenience+Peripheral.swift` into the main `Interface+Peripheral.swift` file as part of some of my refactoring work i'm doing currently, so in the future it should hopefully be a bit more easily discoverable. I'll make a note to improve some doc comments around this pattern as it exists today, as well.
