### ISSUE TITLE
scanForPeripherals never emits if called before CBCentralManager is in the powered on state

### ISSUE THREAD

**Issue by mdelbo** [StarryInternet/CombineCoreBluetooth#27]
Reproduce by call scanForPeripherals as soon as the demo app starts app. You'll see core bluetooth logs an error:

API MISUSE: <private> can only accept this command while in the powered on state

**Comment by klundberg** [comment]
Thanks for reporting, i'll look into it!

**Comment by klundberg** [comment]
I couldn't reproduce the api misuse warning in the central, but I could in the peripheral side, so the pr linked above fixes that issue. Let me know if it fixes what you've run into!

**Comment by BestKai** [comment]
If I call the `scanForPeripherals` function immediately after calling  `let centralManager: CentralManager = .live()`  , I get the same error and cannot receive anything
