### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by SSenocico** [StarryInternet/CombineCoreBluetooth#3]
Hi,

Thank you for sharing with us this library.

Would it be possible to have Carthage support for it?

Thanks!

**Comment by klundberg** [comment]
Hi! That's certainly something I can look into. I don't have a timeline but next time we have some free time, I can try to make that happen.

**Comment by SSenocico** [comment]
Many thanks, @klundberg !

**Comment by gwikiera** [comment]
Hi, 
As well as @SSenocico I need carthage support to use this library, so I've created a PR which adds it https://github.com/StarryInternet/CombineCoreBluetooth/pull/4
@klundberg please take a look 🙏 👁️

**Comment by klundberg** [comment]
Fixed with #4
